title: Betterbox
description: A design tool for effective, ethical technologies
baseurl: /Betterbox
url: https://laurawmcd.github.io 



# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
