title: Betterbox
email: hello@laurawalkermcdonald.com
description: >- # this means to ignore newlines until "baseurl:"
  A design tool for ethical, effective technologies
baseurl: "/betterbox" # the subpath of your site, e.g. /blog
url: "https://laurawmcd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: laurawmcd/betterbox
twitter:
  username: techladylaura
github_username: laurawmcd

header_page_refs:
  - home
  - about
  - blog

# Build settings
theme: jekyll-theme-cayman-blog
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll SEO Tag settings
lang: en_US
social:
  name: Laura Walker McDonald
  links:
    - https://twitter.com/techladylaura
    - https://github.com/laurawmcd

    # Navigation
nav:
  - title: Home
    url: /
  - title: Cards
    url: /cards/
  - title: Users
    url: /cards/users/
  - title: Facilitation/Design
    url: /cards/facilitation-design/
  - title: Practicalities
    url: /cards/practicalities/
  - title: Non-functional Requirements
    url: /cards/non-functional-requirements/
  - title: Values
    url: /cards/values/

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
